import type { Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import './globals.css'
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { ConvexClientProvider } from "./ConvexClientProvider";
import { AuthorizationProvider } from './auth/userauth';

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es">
      <body>
        <ClerkProvider>
          <ConvexClientProvider>

            <AuthorizationProvider>
              <SidebarProvider>
                <AppSidebar />
                <main className="flex-1">
                  <SidebarTrigger />
                  <div className='p-4'>
                    {children}
                  </div>
                </main>
              </SidebarProvider>
            </AuthorizationProvider>

          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}