import Script from 'next/script';
import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css'

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

import { ConvexClientProvider } from "./ConvexClientProvider";
import { AuthorizationProvider } from './auth/userauth';

import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html 
        lang="es" 
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning
      >
        <body className="min-h-screen flex flex-col">

            <ConvexClientProvider>
              <AuthorizationProvider>
                
                <SidebarProvider>
                  <AppSidebar />
                  <main className="flex-1">
                    <SidebarTrigger />
                    <div className='p-4'>
                      {children}
                    </div>
                  </main>
                </SidebarProvider>

              </AuthorizationProvider>

              <Toaster richColors position="top-right" />

            </ConvexClientProvider>

            <Script
              src="https://w.appzi.io/w.js?token=XYtKn"
              strategy="afterInteractive"
            />

        </body>
      </html>
    </ClerkProvider>
  );
}